import { NextPage } from "next";
import Head from "next/head";
import { LoginLayout } from "../../features/login/components/LoginLayout";
import { LoginForm } from "../../features/login/components/LoginForm";

const LoginPage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Login Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="">
				<LoginLayout>
					<LoginForm/>
				</LoginLayout>
			</main>
		</div>
	)
}

export default LoginPage
