import { NextPage } from "next";
import Head from "next/head";
import { VerifyEmailLayout } from "../../../features/verify_email/components/VerifyEmailLayout";
import { VerifyEmailForm } from "../../../features/verify_email/components/VerifyEmailForm";

export const VerifyEmail: NextPage = () => {
	return (
		<div className="">
			<Head>
				<title>Verify Email</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="">
				<VerifyEmailLayout>
					<VerifyEmailForm />
				</VerifyEmailLayout>
			</main>
		</div>
	)
}

export default VerifyEmail
