import { NextPage } from "next";
import Head from "next/head";
import { MainLayout } from "../../components/layout/MainLayout";
import { PrivateLayoutGuard } from "../../components/layout/PrivateLayoutGuard";
import { PrivateLayout } from "../../components/layout/PrivateLayout";
import { SideNavigationContainer } from "../../components/layout/SideNavigationContainer";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { SingleLayout } from "../../features/users/components/SingleLayout";

const ScreenName: NextPage = () => {

	const router = useRouter()
	const [paramsId, setParamsId] = useState('')

	useEffect(() => {
		if (router.isReady) {
			let screen_name = router.query.screen_name
			setParamsId(screen_name as string)
		}
	})

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<MainLayout>
				<PrivateLayoutGuard>
					<PrivateLayout>
						<SideNavigationContainer/>
						<SingleLayout
							screen_name={ paramsId }
						/>
					</PrivateLayout>
				</PrivateLayoutGuard>
			</MainLayout>
		</>
	)
}

export default ScreenName
