import { NextPage } from "next";
import Head from "next/head";
import { ForgotPasswordLayout } from "../../features/forgot_password/conponents/ForgotPasswordLayout";
import { ForgotPasswordForm } from "../../features/forgot_password/conponents/ForgotPasswordForm";

const ForgotPassword: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Forgot password page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-100 h-100">
				<ForgotPasswordLayout>
					<ForgotPasswordForm/>
				</ForgotPasswordLayout>
			</main>
		</div>
	)
}

export default ForgotPassword
