import { NextPage } from "next";
import Head from "next/head";
import Navigation from "../components/navigation";
import styles from "../styles/Users.module.css"

const Users: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h2 className={styles.title}>User List page</h2>

				<Navigation/>
			</main>
		</div>
	)
}

export default Users
