import { NextPage } from "next";
import Head from "next/head";
import { LoginLayout } from "../../features/signin/components/SigninLayout";
import { LoginForm } from "../../features/signin/components/SigninForm";

const LoginPage: NextPage = ({}) => {
	return (
		<div>
			<Head>
				<title>Login Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="">
				<LoginLayout>
					<LoginForm/>
				</LoginLayout>
			</main>
		</div>
	)
}

export async function getStaticProps() {
	return {
		props: {},
	}
}

export default LoginPage
