import { NextPage } from "next"
import Head from "next/head"
import { MyProfileLayout } from "../../features/my_profile/MyProfleLayout"
import { MyAccountEditForm } from "../../features/my_profile/MyAccountEditForm"
import { MyProfileEditForm } from "../../features/my_profile/MyProfileEditForm"

const MyProfile: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Verify Email</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="">
				<MyProfileLayout>
					<MyProfileEditForm />
					<MyAccountEditForm />
				</MyProfileLayout>
			</main>
		</div>
	)
}

export default MyProfile
