import { NextPage } from "next"
import Head from "next/head"
import { MyProfileLayout } from "../../features/my_profile/MyProfleLayout"
import { MyAccountEditForm } from "../../features/my_profile/MyAccountEditForm"
import { MyInfomationEditForm } from "../../features/my_profile/MyInfomationEditForm"
import { SideNavigationContainer } from "../../components/layout/SideNavigationContainer"
import { MainLayout } from "../../components/layout/MainLayout"
import { PrivateLayoutGuard } from "../../components/layout/PrivateLayoutGuard"
import { PrivateLayout } from "../../components/layout/PrivateLayout"
import { MyBasicProfileForm } from "../../features/my_profile/components/MyBasicProfileForm"
import { useMeQuery } from "../../graphql/graphql"

const MyProfile: NextPage = () => {

	const { data, loading, error } = useMeQuery()

	return (
		<div>
			<Head>
				<title>Verify Email</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout>
				<PrivateLayoutGuard>
					<PrivateLayout>
						<SideNavigationContainer/>
						<MyProfileLayout>
							{ loading && (<p>Loading ....</p>)}
							{ data && (
								<>
									<MyInfomationEditForm me={ data.me } />
									<MyBasicProfileForm
										body_type_id={ data.me.user_profile.body_type_id }
										blood_type_id={ data.me.user_profile.blood_type_id }
										occupation_id={ data.me.user_profile.occupation_id }
										education_id={ data.me.user_profile.education_id }
										annual_income_id={ data.me.user_profile.annual_income_id }
										smoking_id={ data.me.user_profile.smoking_id }
										drinking_id={ data.me.user_profile.drinking_id }
									/>
								</>
							)}
						</MyProfileLayout>
					</PrivateLayout>
				</PrivateLayoutGuard>
			</MainLayout>
		</div>
	)
}

export default MyProfile
