import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { MainLayout } from "../../../components/layout/MainLayout";
import { PrivateLayoutGuard } from "../../../components/layout/PrivateLayoutGuard";
import { PrivateLayout } from "../../../components/layout/PrivateLayout";
import { SideNavigationContainer } from "../../../components/layout/SideNavigationContainer";
import { TweetDetail } from "../../../features/[screen_name]/tweet_detail/ui/TweetDetail";
import { TweetDetailLayout } from "../../../features/[screen_name]/tweet_detail/TweetDetailLayout";


const TweetId: NextPage = () => {
	const router = useRouter()
	const [paramsId, setParamsId] = useState('')

	useEffect(() => {
		if (router.isReady) {
			let id = router.query.id
			setParamsId(id as string)
		}
	}, [ router ])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<MainLayout>
				<PrivateLayoutGuard>
					<PrivateLayout>
						<SideNavigationContainer/>
						<TweetDetailLayout>
							<TweetDetail id={ paramsId } />
						</TweetDetailLayout>
					</PrivateLayout>
				</PrivateLayoutGuard>
			</MainLayout>
		</>
	)
}

export default TweetId
