import { NextPage } from "next";
import Head from "next/head";
import { PasswordLayout } from "../../../features/set_password/PasswordLayout";
import { PasswordForm } from "../../../features/set_password/PasswordForm";

const PasswordPage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Set your password page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="">
				<PasswordLayout>
					<PasswordForm/>
				</PasswordLayout>
			</main>
		</div>
	)
}

export default PasswordPage
