import Head from "next/head"
import { SideNavigationContainer } from "../../components/layout/SideNavigationContainer"
import { useUserSearchFilters } from "../../hooks/useUserSearchFilters"
import { MainLayout } from "../../components/layout/MainLayout"
import { PrivateLayoutGuard } from "../../components/layout/PrivateLayoutGuard"
import { PrivateLayout } from "../../components/layout/PrivateLayout"
import { UserSearchFilterLayout } from "../../features/user_search_filters/layout/UserSearchFilterLayout"
import { UserSearchFilterForm } from "../../features/user_search_filters/components/UserSearchFilterForm"

const UserSearchFilters = () => {

	const userSearchFilter = useUserSearchFilters()

	return (
		<div className="">
			<Head>
				<title>ユーザー検索フィルター</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout>
				<PrivateLayoutGuard>
					<PrivateLayout>
						<SideNavigationContainer/>
							<UserSearchFilterLayout>
								{ userSearchFilter && (
									<>
										<UserSearchFilterForm
											userSearchFilter={ userSearchFilter }
										/>
									</>
								)}
							</UserSearchFilterLayout>
						</PrivateLayout>
				</PrivateLayoutGuard>
			</MainLayout>
		</div>
	)
}

export default UserSearchFilters
