import { NextPage } from "next";
import Head from "next/head";
import { SignupLayout } from "../../features/signup/components/SignupLayout";
import { SignupForm } from "../../features/signup/components/SignupForm";

const Signup: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Signup Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="">
				<SignupLayout>
					<SignupForm />
				</SignupLayout>
			</main>
		</div>
	)
}

export default Signup
