import { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Users.module.css"
import { useUsersQuery } from "../../graphql/graphql";
import { PrivateLayoutGuard } from "../../components/layout/PrivateLayoutGuard";
import { MainLayout } from "../../components/layout/MainLayout";
import { PrivateLayout } from "../../components/layout/PrivateLayout";
import { SideNavigationContainer } from "../../components/layout/SideNavigationContainer";
import { UserLists } from "../../features/users/components/UserLists";

const UsersPage: NextPage = () => {
	const { data, loading, error } = useUsersQuery({
		variables: {
			first: 30,
			after: "",
		}
	})

	// if (loading) return <p>Now Loading .....</p>
	// if (error) return <p className='font-bold text-3xl'>error</p>

	return (
		<>
			<Head>
				<title>User List Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout>
				<PrivateLayoutGuard>
					<PrivateLayout>
						<SideNavigationContainer/>
						<UserLists
							data={ data }
						/>
					</PrivateLayout>
				</PrivateLayoutGuard>
			</MainLayout>
		</>
	)
}

export default UsersPage
